# Generated by Django 3.2.4 on 2021-06-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
    ]
